#!/bin/bash
###############################################################################
# This script is to tune the ACOTSP software.
#
# PARAMETERS:
# $1 is the ID of the candidate to be evaluated
# $2 is the c2 ID
# $3 is the c1
# $4 is the c2 name
# The rest ($* after `shift 4') are parameters for running ACOTSP
#
# RETURN VALUE:
# This script should print a single numerical value (the value to be minimized).
###############################################################################
python call_cs.py --nfe 1e+4 --n $5 --k $6 --pr $7 --bbob "function_indices:17 dimensions:2 instance_indices:1"

exit 0
